# Generated by Django 3.2.9 on 2021-11-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('numSubscrible', models.IntegerField()),
            ],
            options={
                'db_table': 'video_users',
            },
        ),
    ]
