# Generated by Django 3.2.9 on 2021-11-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('videoid', models.IntegerField()),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'video_comments',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videoid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('videourl', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('size', models.FloatField()),
                ('numsLikes', models.FloatField()),
                ('numsDisLikes', models.FloatField()),
                ('numViews', models.FloatField()),
            ],
            options={
                'db_table': 'video_details',
            },
        ),
    ]
